service: tenjin

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: eu-west-1

functions:
  auth:
    handler: src/handler.auth
    environment:
      CLIENT_ID: ${env:CLIENT_ID}
      CLIENT_SECRET: ${env:CLIENT_SECRET}
    events:
      - http:
          path: /
          method: get
          cors: true
